Expression = Term, T2;

T2 = '+', Term, T2
   | '-', Term, T2
   | '';

Term = Factor, F2;

F2 = '*', Factor, F2
   | '/', Factor, F2
   | '';

Factor = '(', Expression, ')'
       | '-', Factor
       | Natural;

Natural = { Digit };

Digit = '0' | '1' | '2' | '3' | '4'
      | '5' | '6' | '7' | '8' | '9';
